recipe: default.v1

language: es

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer

policies:
  - name: RulePolicy

models:
  - type: LLM
    provider: ollama
    model: qwen2.5:0.5b
    url: http://localhost:11434
assistant_id: 20260503-103401-watery-engine
