recipe: default.v1

language: es

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CompactLLMCommandGenerator
    llm:
      model_group: gemini_llm
    prompt_template: prompts/custom-command-template.jinja2
    flow_retrieval:
      active: false

policies:
  - name: FlowPolicy
  - name: RulePolicy

assistant_id: farmarag-rasa-calm
