export const colors = {
  primary: '#00685f',
  'primary-container': '#008378',
  'on-primary': '#ffffff',
  'on-primary-container': '#f4fffc',
  surface: '#f5faf8',
  'surface-container-low': '#f0f5f2',
  'surface-container-high': '#e4e9e7',
  'surface-container-highest': '#dee4e1',
  'surface-variant': '#dee4e1',
  'on-surface': '#171d1c',
  'on-surface-variant': '#3d4947',
  'text-main': '#334155',
  'text-muted': '#64748B',
  error: '#ba1a1a',
  'error-container': '#ffdad6',
  'on-error': '#ffffff',
  'on-error-container': '#93000a',
  secondary: '#006c49',
  'secondary-container': '#6cf8bb',
  'on-secondary': '#ffffff',
  'on-secondary-container': '#00714d',
  tertiary: '#924628',
  'tertiary-container': '#b05e3d',
  'on-tertiary': '#ffffff',
  'on-tertiary-container': '#fffbff',
  'tertiary-fixed': '#ffdbce',
  'tertiary-fixed-dim': '#ffb59a',
  'primary-fixed': '#89f5e7',
  'primary-fixed-dim': '#6bd8cb',
  'on-primary-fixed': '#00201d',
  'on-primary-fixed-variant': '#005049',
  'secondary-fixed': '#6ffbbe',
  'secondary-fixed-dim': '#4edea3',
  'on-secondary-fixed': '#002113',
  'on-secondary-fixed-variant': '#005236',
  'inverse-surface': '#2c3130',
  'inverse-on-surface': '#edf2f0',
  'inverse-primary': '#6bd8cb',
  outline: '#6d7a77',
  'outline-variant': '#bcc9c6',
  'surface-dim': '#d6dbd9',
  'surface-bright': '#f5faf8',
  'surface-tint': '#006a61',
  'surface-base': '#F8FAFC',
  'surface-panel': '#F1F5F9',
  'surface-container': '#eaefed',
  'surface-container-lowest': '#ffffff',
  'error-surface': '#FEF2F2',
  'error-border': '#FEE2E2',
  'status-online': '#10B981',
  'status-offline': '#EF4444',
};

export const spacing = {
  'stack-md': '1rem',
  'stack-sm': '0.5rem',
  'bubble-gap': '1rem',
  'container-padding': '1.5rem',
  'panel-width': '420px',
};

export const fonts = {
  h1: 'Manrope, sans-serif',
  body: 'Inter, sans-serif',
  label: 'Inter, sans-serif',
};

export const fontSizes = {
  h1: ['24px', { lineHeight: '1.2', letterSpacing: '-0.025em', fontWeight: '900' }],
  body: ['14px', { lineHeight: '1.625', fontWeight: '400' }],
  label: ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
};